id: 4e15e872157e4da081501fa7cc5b4a27
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_164-The_Questions_of_Ratnacandra-v2
  language: en
  author: ''
  volume: {}
